### ISSUE TITLE
Fixed form field height limits customizability

### ISSUE THREAD

**Issue by chrislloyd** [basscss/base-forms#2]
We were building a form with multiple different sizes of text input (`.field.h1`) and found that the text was clipped because the `height` attribute is set on all form fields (https://github.com/basscss/base-forms/blob/master/index.css#L31). It would be more flexible if the fields (or at least text based fields) were controlled with `line-height`.

Any objections or prior knowledge before I make this change?

**Comment by jxnblk** [comment]
There are issues with previous versions of Firefox and setting height and line height on form elements. The styles used in basscss are written in a way to make sure form elements and buttons all align vertically by default, so I'd say it's kind of fragile.

You can take a stab at it, but I'd want to test it in the older browsers and in a few different contexts.

I think the preferred way to handle multiple sizes of form elements would be with extensions like `.input-big` like in Bootstrap.

**Comment by chrislloyd** [comment]
Hrrrm, sounds tricky. Had forgotten about the dark ages of Firefox. Might leave this one for the moment and come up with our own sizes.

**Comment by jxnblk** [comment]
FWIW, I do plan on exploring this again, since I do like the idea of using ems to resize form elements.

**Comment by jxnblk** [comment]
I explored using ems for form field and button sizing and decided against it. Mostly because currently having the ability to adjust the font-size for buttons independent of form fields but keeping the overall size the same seems like good separation of concerns.

For example, I often keep form elements at 1rem due to accessibility and zooming issues on mobile devices, but adjust the button size to .875rem for visual balance.

That said, to address your original issue, I would suggest using something like `.field-big` to adjust the height in one-off cases.

**Comment by chrislloyd** [comment]
Sounds solid :+1:
